FPIDjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import include, path


__author__ = '(Multiple)'
__project__ = "Food-Pantry-Inventory"
__creation_date__ = "04/01/2019"


urlpatterns = [
    path('', LoginView.as_view(template_name='fpiweb/login.html')),
    path('fpiweb/', include('fpiweb.urls')),
    path('warmadmin/', admin.site.urls,),

]

# required for django-debug-toolbar

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns


# EOF

fpiweb/urls.py
"""
Manage the urls for the F. P. I. application.
"""

from django.urls import path
from django.contrib.auth.views import \
    LoginView, \
    LogoutView, \
    PasswordChangeView

from fpiweb.views import \
    AboutView, \
    ActivityDownloadView, \
    BoxDetailsView, \
    BoxEditView, \
    BoxEmptyMoveView, \
    BoxEmptyView, \
    BoxItemFormView, \
    BoxMoveView, \
    BoxNewView, \
    BoxScannedView, \
    BoxTypeMaintenanceListView, \
    BoxTypeMaintenanceCreateView, \
    BoxTypeMaintenanceUpdateView, \
    BoxTypeMaintenanceDeleteView, \
    BuildPalletView, \
    ConstraintCreateView, \
    ConstraintDeleteView, \
    ConstraintsListView, \
    ConstraintUpdateView, \
    IndexView, \
    LocBinCreateView, \
    LocBinDeleteView, \
    LocBinListView, \
    LocBinUpdateView, \
    LocRowCreateView, \
    LocRowDeleteView, \
    LocRowListView, \
    LocRowUpdateView, \
    LocTierCreateView, \
    LocTierDeleteView, \
    LocTierListView, \
    LocTierUpdateView, \
    ConfirmPasswordChangeView, \
    MaintenanceView, \
    ManualBoxStatusView, \
    ManualCheckinBoxView, \
    ManualConsumeBoxView, \
    ManualMoveBoxView, \
    ManualNewBoxView, \
    ManualPalletMoveView, \
    ProductCategoryCreateView, \
    TestScanView, \
    UserManagementView, \
    UserCreateview, \
    UserUpdateView, \
    ProductCategoryListView, \
    ProductCategoryUpdateView, \
    ProductNameListView, \
    ProductNameCreateView, \
    ProductNameUpdateView, \
    ProductExampleUpdateView, \
    ProductExampleCreateView, \
    ProductExampleDeleteView, \
    ProductExampleListView, \
    ManualLocTableListView, \
    ManualLocTableCreateView, \
    ManualLocTableUpdateView, \
    RebuildLocTableStartView, \
    RebuildLocTableFinishView, \
    RebuildLocTableProgressView
from fpiweb.fpiweb_views.PrintLabelView import \
    PrintLabelView


__author__ = '(Multiple)'
__project__ = "Food-Pantry-Inventory"
__creation_date__ = "09/15/2020"

# set the namespace for the application
app_name = 'fpiweb'

urlpatterns = [

    # index page
    # e.g. /fpiweb/ or /fpiweb/index/
    path('', IndexView.as_view(), name='index'),
    path('index/', IndexView.as_view(), name='index'),

    # about page
    # e.g. /fpiweb/about/
    path('about/', AboutView.as_view(), name='about'),

    # login page
    # e.g. /fpiweb/login/
    path(
        'login/',
        LoginView.as_view(
            template_name='fpiweb/login.html'
        ),
        name='login'
    ),

    # change password page
    # e.g. /fpiweb/change_pswd/
    # path('change_pswd/', ChangePasswordView.as_view(), name='change_pswd'),
    path(
        'change_pswd/',
        PasswordChangeView.as_view(
            template_name='fpiweb/change_password.html',
            success_url='/fpiweb/confirm_pswd',
        ),
        name='change_pswd',
    ),

    # confirm password page
    # e.g. /fpiweb/confirm_pswd/
    path(
        'confirm_pswd/',
        ConfirmPasswordChangeView.as_view(),
        name='confirm_pwsd',
    ),

    # logout page
    # e.g. /fpiweb/logout/
    path(
        'logout/',
        LogoutView.as_view(
            template_name='fpiweb/logout.html',
        ),
        name='logout',
    ),

    # Maintenance page
    # e.g. /fpiweb/maintenance/ = list of constraints
    path('maintenance/', MaintenanceView.as_view(),
         name='maintenance'),

    # LocRow List page
    # e.g. /fpiweb/loc_rows/ = list of loc_rows
    path('loc_row/', LocRowListView.as_view(),
         name='loc_row_view'),

    # LocRow Add page
    # e.g. /fpiweb/loc_row/add/ = add a loc_row
    path('loc_row/add/', LocRowCreateView.as_view(),
         name='loc_row_new', ),

    # LocRow Edit page
    # e.g. /fpiweb/loc_row/edit/4/ = edit loc_row # 4
    path('loc_row/edit/<int:pk>/', LocRowUpdateView.as_view(),
         name='loc_row_update', ),

    # LocRow Delete Page
    # e.g. /fpiweb/loc_row/delete/4/ = delete loc_row # 4
    path('loc_row/delete/<int:pk>/', LocRowDeleteView.as_view(),
         name='loc_row_delete', ),

    # LocBin List page
    # e.g. /fpiweb/loc_bins/ = list of loc_bins
    path('loc_bin/', LocBinListView.as_view(),
         name='loc_bin_view'),

    # LocBin Add page
    # e.g. /fpiweb/loc_bin/add/ = add a loc_bin
    path('loc_bin/add/', LocBinCreateView.as_view(),
         name='loc_bin_new', ),

    # LocBin Edit page
    # e.g. /fpiweb/loc_bin/edit/4/ = edit loc_bin # 4
    path('loc_bin/edit/<int:pk>/', LocBinUpdateView.as_view(),
         name='loc_bin_update', ),

    # LocBin Delete Page
    # e.g. /fpiweb/loc_bin/delete/4/ = delete loc_bin # 4
    path('loc_bin/delete/<int:pk>/', LocBinDeleteView.as_view(),
         name='loc_bin_delete', ),

    # LocTier List page
    # e.g. /fpiweb/loc_tiers/ = list of loc_tiers
    path('loc_tier/', LocTierListView.as_view(),
         name='loc_tier_view'),

    # LocTier Add page
    # e.g. /fpiweb/loc_tier/add/ = add a loc_tier
    path('loc_tier/add/', LocTierCreateView.as_view(),
         name='loc_tier_new', ),

    # LocTier Edit page
    # e.g. /fpiweb/loc_tier/edit/4/ = edit loc_tier # 4
    path('loc_tier/edit/<int:pk>/', LocTierUpdateView.as_view(),
         name='loc_tier_update', ),

    # LocTier Delete Page
    # e.g. /fpiweb/loc_tier/delete/4/ = delete loc_tier # 4
    path('loc_tier/delete/<int:pk>/', LocTierDeleteView.as_view(),
         name='loc_tier_delete', ),

    # Constraint List page
    # e.g. /fpiweb/constraints/ = list of constraints
    path('constraints/', ConstraintsListView.as_view(),
         name='constraints_view'),

    # Constraint Add page
    # e.g. /fpiweb/constraint/add/ = add a constraint
    path('constraint/add/', ConstraintCreateView.as_view(),
         name='constraint_new', ),

    # Constraint Edit page
    # e.g. /fpiweb/constraint/edit/4/ = edit constraint # 4
    path('constraint/edit/<int:pk>/', ConstraintUpdateView.as_view(),
         name='constraint_update', ),

    # Constraint Delete Page
    # e.g. /fpiweb/constraint/delete/4/ = delete constraint # 4
    path('constraint/delete/<int:pk>/', ConstraintDeleteView.as_view(),
         name='constraint_delete', ),

    # Box Add page
    # e.g.  /fpiweb/box/add/ = add a box to inventory
    path('box/new/<str:box_number>/', BoxNewView.as_view(), name='box_new'),

    # Box Edit page
    # e.g. /fpiweb/box/<pk>/edit = edit a box in inventory
    path('box/<int:pk>/edit/', BoxEditView.as_view(), name='box_edit'),

    # Box Detail page
    # e.g. /fpiweb/box/<pk>/ = view the information about a box
    path('box/<int:pk>/', BoxDetailsView.as_view(), name='box_details'),

    # Box scan page (QR code scans will start here)
    # e.g. /fpiweb/box/box12345/ = view the information about a box
    path('box/box<int:number>/', BoxScannedView.as_view(), name='box_scanned'),

    # Move or empty a box
    # e.g. /fpiweb/box/<pk>/empty_move = consume or move a box
    path('box/<int:pk>/empty_move/', BoxEmptyMoveView.as_view(),
         name='box_empty_move'),

    # Move a box
    # e.g. /fpiweb/box/<pk>/move/ = change location of box in inventory
    path('box/<int:pk>/move/', BoxMoveView.as_view(), name='box_move'),

    # fill a box
    # e.g. /fpiweb/box/<pk>/fill/ = fill an empy box and put in inventory
    path('box/<int:pk>/fill/', BoxEmptyMoveView.as_view(), name='box_fill'),

    # Empty a box
    # e.g. /fpiweb/box/<pk>/empty = consume the product in a box
    path('box/<int:pk>/empty/', BoxEmptyMoveView.as_view(), name='box_empty'),

    # send scan image or box number to server receive JSON info on box
    path('box/box_form/', BoxItemFormView.as_view(), name='box_form'),

    # e.g. /fpiweb/test_scan/ = ???
    path('test_scan/', TestScanView.as_view(), name='test_scan'),

    # Add a box to a pallet view
    # e.g. /fpiweb/build_pallet/box/box12345/ = add a box to existing pallet
    path(
        'build_pallet/<str:box_number>/',
        BuildPalletView.as_view(),
        {'box_pk': 'pk'},
        name='build_pallet_add_box'
    ),

    # Start a new pallet view
    # e.g. /fpiweb/build_pallet/ = start a new pallet
    path(
        'build_pallet/',
        BuildPalletView.as_view(),
        name='build_pallet'
    ),

    # Move all boxes in one location to a different location
    # e.g. /fpiweb/manual_pallet_move/
    path(
        'manual_pallet_move/',
        ManualPalletMoveView.as_view(),
        name='manual_pallet_move',
    ),

    # build a pallet of boxes and store in a given location
    path('build_pallet/', BuildPalletView.as_view(), name='build_pallet'),

    # generate a pdf of one or more pages of QR code labels to put on boxes
    # e.g. /fpiweb/print_labels/
    path('print_labels/', PrintLabelView.as_view(), name='print_labels'),

    # Downlaod a csv file containinng all box activity
    # e.g. /fpiweb/activity/download/
    path(
        'activity/download/',
        ActivityDownloadView.as_view(),
        name='download_activities'),

    # Manually add an empty box to the inventory system
    # e.g. /fpiweb/manual_box_status/ = add a box to the system
    path('manual_add_box/', ManualNewBoxView.as_view(),
         name='manual_add_box', ),

    # Manually check in a box
    # e.g. /fpiweb/manual_checkin_box/ = check in a box manually
    path(
        'manual_checkin_box/',
        ManualCheckinBoxView.as_view(),
        name='manual_checkin_box',
    ),

    # Manually check out a box
    # e.g. /fpiweb/manual_checkout_box/ = check out a box manually
    path(
        'manual_checkout_box/',
        ManualConsumeBoxView.as_view(),
        name='manual_checkout_box',
    ),

    # Manually move a filled box
    # e.g. /fpiweb/manual_move_box/ = move a filled box manually
    path(
        'manual_move_box/',
        ManualMoveBoxView.as_view(),
        name='manual_move_box',
    ),

    # Manually get a box status
    # e.g. /fpiweb/manual_box_status/ = determine the status of a box manually
    path(
        'manual_box_status/',

fpiweb/templates/fpiweb/box_detail.html
{% extends 'fpiweb/base.html' %}

{% block title %}
Box Details
{% endblock %}

{% block content %}


<div>
    <a class="btn btn-primary" href="{% url 'fpiweb:index' %}">Home</a>
</div>

<div>{{ box.box_number }}</div>

<div class="row"><span>Box Type:</span>&nbsp; {{ box.box_type.box_type_descr }}</div>
<div class="row">Location</div>
<div class="row">
    <div class="col-md-2">
        <table>
            <tr>
                <th>Row</th>
                <th>Bin</th>
                <th>Tier</th>
            </tr>
            <tr>
                <td>{{ box.loc_row|default_if_none:"&nbsp;" }}</td>
                <td>{{ box.loc_bin|default_if_none:"&nbsp;" }}</td>
                <td>{{ box.loc_tier|default_if_none:"&nbsp;" }}</td>
            </tr>
        </table>
    </div>
    <div class="col-md-1">
        <a class="btn btn-primary" href="{% url 'fpiweb:box_move' box.pk %}">Move</a>
    </div>
</div>
<div class="row">Contents</div>
<div class="row"><span>Product:</span> {{ box.product.prod_name }}</div>
<div class="row">Expiration</div>
<div class="row"><span>Year:</span> {{ box.exp_year|default_if_none:"" }}</div>
<div class="row">
    <span>Month:</span>
    {% if box.exp_month_start %}
        {{ box.exp_month_start }} - {{ box.exp_month_end }}
    {% endif %}
</div>
<div class="row">
{% if box.product %}
    <a class="btn btn-primary" href="{% url 'fpiweb:box_empty' box.pk %}">Empty</a>
{% else %}
    <a class="btn btn-primary" href="{% url 'fpiweb:box_fill' box.pk %}">Fill</a>
{% endif %}
</div>

{% endblock %}

fpiweb/templates/fpiweb/box_fill.html
{% extends 'fpiweb/base.html' %}
{% load bootstrap4 %}

{% block title %}Fill Box{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-4 text-center">
            <h1 class="h1">Fill Box</h1>
        </div>
    </div>

    {% if form.non_field_errors %}
      <div class="alert alert-danger">
        <ul>
        {% for error in form.non_field_errors %}
          <li>{{ error }}</li>
        {% endfor %}
        </ul>
      </div>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_field form.product %}
        {% bootstrap_field form.exp_year %}
        {% bootstrap_field form.exp_month_start %}
        {% bootstrap_field form.exp_month_end %}
        <input type="submit" value="Submit"/>
    </form>

{% endblock %}

fpiweb/templates/fpiweb/box_type_maintence_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

fpiweb/templates/fpiweb/change_password.html
{% extends 'fpiweb/base.html' %}
{% load bootstrap4 %}
{% comment %}

CONTEXT VARIABLES
-----------------
form: Standard Django PasswordChangeForm

{% endcomment %}
{% block title %}
    Change password
{% endblock %}

{% block content %}
    <div>
        <h1>
            Change Password
        </h1>
    </div>
    <div>
      <a href="{% url 'fpiweb:index' %}">Return to main page.</a>
    </div>

    <div class="text-center">
        <p>user {{ user }}</p>
    </div>

    <form action="" method="post">
        {% csrf_token %}
        <div>
            {% bootstrap_field form.old_password %}
            {% bootstrap_field form.new_password1 %}
            {% bootstrap_field form.new_password2 %}
        </div>
        <div class="row">
            <button type="submit"
                    class="btn btn-primary">Change Password</button>
        </div>
    </form>
  
    <hr/>

    <div>
        <a href="{% url 'fpiweb:index' %}">Return to main page.</a>
    </div>

{% endblock %}

fpiweb/templates/fpiweb/confirm_password_change.html
{% extends 'fpiweb/base.html' %}

{% block title %}
    Confirm Password
{% endblock %}

{% block content %}
    <div>
        <h1>
            Confirm Password Changed
        </h1>
    </div>
    <br/>

    <div class="text-center">

    <h2>
        {{ user_info.user.first_name }} &nbsp;
        {{ user_info.user.last_name }}
    </h2>
    <h3>
        {{ user_info.profile.title }}
        ({{ user_info.highest_access_level.name }})
    </h3>
    </div>

    <div>
    Your password has been successfully changed.  Please add it to your
        password manager or keep it in a secure and inobvious place.
    </div>
    <hr/>

    <div>
        <a href="{% url 'fpiweb:index' %}">Return to main page.</a>
    </div>

{% endblock %}

fpiweb/templates/fpiweb/constraints_list.html
{% extends 'fpiweb/base.html' %}

{# Purpose: List all constraints #}
{# URL Name constraints_view #}
{# URL response: GET #}
{# Table: Constraints #}
{# form: none #}

{% block title %}Constraint List{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="h1">
                Constraints List
            </h1>
        </div>
    </div>

    <hr class="style-one"/>

    <div class="row">
        &nbsp;
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            <a class="btn alert-info"
               role="button"
               href="{% url 'fpiweb:constraint_new' %}">
                Add a Constraint
            </a>
        </div>
    </div>

    <div class="row">
        &nbsp;
    </div>

    <div class="row text-center">
        <div class="col-md-3"><strong>Name</strong></div>
        <div class="col-md-2"><strong>Type</strong></div>
        <div class="col-md-3"><strong>Valid Values</strong></div>
        <div class="col-md-2 text-center">
            <strong>Edit this constraint</strong>
        </div>
        <div class="col-md-2 text-center">
            <strong>Delete this constraint</strong>
        </div>
    </div>


    {% if object_list %}
        {% for constraint in object_list %}
            <div class="row text-left">
                <div class="col-md-3">
                    {{ constraint.constraint_name|safe }}
                </div>
                <div class="col-md-2">
                    {{ constraint.constraint_type }}
                </div>
                {% if constraint.constraint_type  in range_list %}
                    <div class="col-md-3">
                        Range: {{ constraint.constraint_min | safe }}
                        through {{ constraint.constraint_max | safe }}
                    </div>
                {% else %}
                    <div class="col-md-3">
                        Valid List: {{ constraint.constraint_list | safe }}
                    </div>
                {% endif %}
                <div class="col-md-2">
                    <div class="text-center">
                        <a class="btn alert-info"
                           role="button"
                           href="
                            {% url 'fpiweb:constraint_update' pk=constraint.id %}">
                            Edit
                        </a>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="text-center">
                        <a class="btn alert-info"
                           role="button"
                           href="
                            {% url 'fpiweb:constraint_delete' pk=constraint.id %}">
                            Delete
                        </a>
                    </div>
                </div>
            </div>
            <div class="row text-left">
                <div class="col-md-1">
                    &nbsp;
                </div>
                <div class="col-md-11">
                    {{ constraint.constraint_descr }}
                    <hr class="style-one"/>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No constraints are available.</p>
    {% endif %}
    <div class='row'>
        <a href="{% url 'fpiweb:maintenance' %}">
            Return to system maintenance
        </a>
    </div>


    <hr class="style-one"/>

    <h6>
        Template: constraint_list.html
    </h6>
    <h6>
        View: ConstraintsListView
    </h6>
    <h6>
        Add URL: {% url 'fpiweb:constraint_new' %}
    </h6>
    <h6>
        Edit URL: {% url 'fpiweb:constraint_update' pk=1 %}
    </h6>
    <h6>
        Delete URL: {% url 'fpiweb:constraint_delete' pk=1 %}
    </h6>

{% endblock %}

fpiweb/templates/fpiweb/loc_row_delete.html
{% extends 'fpiweb/base.html' %}

{# Purpose - Confirm delete of a row. #}
{# URL Name - loc_row_delete #}
{# URL Response - POST #}
{# Table - LocRow #}
{# Form - none #}

{% block title %}
    Delete Row
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="h1">
                Delete Row
            </h1>
         </div>
    </div>

    <div class="row">
        &nbsp;
    </div>

    <div class="row">
            <div class="col-md-12 text-center">
                <strong>
                    Are you sure you want to delete this row
                    {{ loc_row.loc_row }} - {{ loc_row.loc_row_descr }}?
                </strong>
            </div>
    </div>

    <div class="row">
        &nbsp;
    </div>

    <form action="
            {%  url 'fpiweb:loc_row_delete' pk=loc_row.id %}"
          method="POST">
        {% csrf_token %}

        <div class="row">
            <div class="col-md-12 text-center">
                <button id="delete_row"
                        type="submit"
                        class="btn btn-default alert-success">
                    Confirm
                </button>
            </div>
        </div>

         <br />

        <div class="row">
            <div class="col-md-12 text-center">
                <a class="btn alert-info"
                   role="button"
                   href="{% url 'fpiweb:loc_row_view' %}">
                    Cancel
                </a>
            </div>
        </div>
    </form>

    <hr class="style-one">

    <h6>
        Template: loc_row_delete.html
    </h6>
    <h6>
        View: LocRowDelete
    </h6>
    <h6>
        Delete URL: {%  url 'fpiweb:loc_row_delete' pk=1 %}
    </h6>
    <h6>
        Cancel URL: {% url 'fpiweb:loc_row_view' %}
    </h6>

{% endblock %}

fpiweb/templates/fpiweb/loc_tier_delete.html
{% extends 'fpiweb/base.html' %}

{# Purpose - Confirm delete of a tier. #}
{# URL Name - loc_tier_delete #}
{# URL Response - POST #}
{# Table - LocTier #}
{# Form - none #}

{% block title %}
    Delete Tier
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="h1">
                Delete Tier
            </h1>
         </div>
    </div>

    <div class="row">
        &nbsp;
    </div>

    <div class="row">
            <div class="col-md-12 text-center">
                <strong>
                    Are you sure you want to delete this tier
                    {{ loc_tier.loc_tier }} - {{ loc_tier.loc_tier_descr }}?
                </strong>
            </div>
    </div>

    <div class="row">
        &nbsp;
    </div>

    <form action="
            {%  url 'fpiweb:loc_tier_delete' pk=loc_tier.id %}"
          method="POST">
        {% csrf_token %}

        <div class="row">
            <div class="col-md-12 text-center">
                <button id="delete_tier"
                        type="submit"
                        class="btn btn-default alert-success">
                    Confirm
                </button>
            </div>
        </div>

         <br />

        <div class="row">
            <div class="col-md-12 text-center">
                <a class="btn alert-info"
                   role="button"
                   href="{% url 'fpiweb:loc_tier_view' %}">
                    Cancel
                </a>
            </div>
        </div>
    </form>

    <hr class="style-one">

    <h6>
        Template: loc_tier_delete.html
    </h6>
    <h6>
        View: LocTierDelete
    </h6>
    <h6>
        Delete URL: {%  url 'fpiweb:loc_tier_delete' pk=1 %}
    </h6>
    <h6>
        Cancel URL: {% url 'fpiweb:loc_tier_view' %}
    </h6>

{% endblock %}

fpiweb/templates/fpiweb/manual_box_type.html
{% extends 'fpiweb/base.html' %}

{% block title %}
    About Food Pantry Inventory
{% endblock %}

{% block content %}
    <div>
        <h1>
            About the Food Pantry Inventory System
        </h1>
    </div>
    <br/>

    <div class="col-md-11">
        <div class="text-center">
            <h2>
                {{ site_name }}
            </h2>
        </div>
        <h3>
            {{ site_address }}
            <br/>
            {{ site_csz }}
            <br/>
            {{ site_phone }}
            <br/>
            <a href="{{ site_url }}">{{ site_url }}</a>

        </h3>
    </div>

    <div>
        <a href="{% url 'fpiweb:index' %}">Return to main page.</a>
    </div>

{% endblock %}

fpiweb/templates/fpiweb/manual_check_in_box.html
{% extends 'fpiweb/base.html' %}
{% load bootstrap4 %}
{% comment %}

CONTEXT VARIABLES
-----------------
mode                   string indicating mode.  Constants are defined
                       for this in the ManualCheckinBoxView class.
box_number_form        An ExtantBoxNumberForm
box                    A Box instance
product_form           An ExistingProductForm
product                A Product instance
location_form          An ExistingLocationForm
location               A Location instance
exp_year_form          A form for selecting the expiration year
exp_year               The selected expiratioh year
exp_moonth_start_form  A form for selecting the expiration starting month
exp_month_start        Starting month of expiration range - if specified
exp_month_end_form     A form for selecting the expiration ending month
exp_month_end          Ending month of expiration range - if specified
view_class             Reference to ManualCheckinBoxView
errors                 A list of errors.

{% endcomment %}

{% block title %}
    Checkin a Box
{% endblock %}

{% block content %}

    <h1>Check In a Box</h1>

    {% if errors %}
        <div class="alert alert-danger">
            <ul>
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}


    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="mode" value="{{ mode }}"/>

        {% if mode == view_class.MODE_ENTER_BOX_INFO %}

            <h3>What number is on the box?</h3>
            <div class="row">
                {% bootstrap_field box_number_form.box_number show_help=False %}
            </div>

            <h3>What product is in box?</h3>

            <div class="row">
                {% bootstrap_field product_form.product show_help=False %}
            </div>

            <h3>Where will the box go (pallet location)?</h3>

            <div class="row">
                {% bootstrap_field location_form.loc_row show_help=False %}
            </div>
            <div class="row">
                {% bootstrap_field location_form.loc_bin show_help=False %}
            </div>
            <div class="row">
                {% bootstrap_field location_form.loc_tier show_help=False %}
            </div>

            <h3>What expiration year is on the box?</h3>

            <div class="row">
                {% bootstrap_field exp_year_form.exp_year show_help=False %}
            </div>

            <h3>If a month range label is on the box, what are the starting
                and ending months?</h3>

            <div class="row">
                {% bootstrap_field exp_month_start_form.exp_month_start show_help=False %}
            </div>

            <div class="row">
                {% bootstrap_field exp_month_end_form.exp_month_end show_help=False %}
            </div>

            <div class="row">
                <input type="submit" class="btn btn-primary"
                       value="Set Box Checkin Information"/>
            </div>

        {% elif mode == view_class.MODE_CONFIRMATION %}
            <div class="row">
                Confirmed:
                Box {{ box.box_number }} has been successfully
                filled with {{ product.prod_name }}
                which expires {{ box.exp_year }}
                {% if box.exp_month_start %}
                    ({{ box.exp_month_start }} to {{ box.exp_month_end }})
                {% endif %}
                and is now located at {{ location.loc_descr }},
            </div>
        {% else %}
            <div class="alert alert-danger">Mode is &quot;{{ mode }}&quot;</div>
        {% endif %}

        <br/>

        <div>
            <a href="{% url 'fpiweb:index' %}">
                {% if mode == view_class.MODE_CONFIRMATION %}
                    Return to Main Menu</a>
                {% else %}
                    Cancel Box Check In
                {% endif %}
            </a>
        </div>
    </form>


{% endblock %}